### PR TITLE
Automatically change api if can't connect.

### PR DESCRIPTION
**Pull request by nguyenvancaokyfpt**

### CODE REVIEW

**Comment by SegoCode** [comment]
Interesting, I understand what you want to do but I see some improvements,

Here:
https://github.com/SegoCode/swd/pull/8/commits/feff9eb52aae1fcbfb8b955a8fcd132b38a2ead8#diff-2ceec6071e325b949b0bccb33ceb78b914835960a97b33f64912882cf3d22b28R121-R126

I just can send a one parameter or ``--node`` or ``--downloadFormat`` but never both at the same time, maybe its time to use flags https://gobyexample.com/command-line-flags

And in this loop:
https://github.com/SegoCode/swd/pull/8/commits/feff9eb52aae1fcbfb8b955a8fcd132b38a2ead8#diff-2ceec6071e325b949b0bccb33ceb78b914835960a97b33f64912882cf3d22b28R154

Maybe you should add +1 to the actual node to show the next node to try in the output

And again thank you for contributing 💕

**Comment by Cod3dDOT** [comment]
NODE can be from 4 to 8, while your code suggests the range from 0 to 8:

Taken from steamworkshopdownloader.io:

```
window.resetBackendNodeId = function() {
  return $a = Xa + Math.round(Math.random() * (Qa - Xa))
}
```

Where Xa = 4, Qa = 8

**Comment by SegoCode** [comment]
Good point @Cod3dDOT

**Comment by nguyenvancaokyfpt** [comment]
> Interesting, I understand what you want to do but I see some improvements,
> 
> Here: [feff9eb#diff-2ceec6071e325b949b0bccb33ceb78b914835960a97b33f64912882cf3d22b28R121-R126](https://github.com/SegoCode/swd/commit/feff9eb52aae1fcbfb8b955a8fcd132b38a2ead8#diff-2ceec6071e325b949b0bccb33ceb78b914835960a97b33f64912882cf3d22b28R121-R126)
> 
> I just can send a one parameter or `--node` or `--downloadFormat` but never both at the same time, maybe its time to use flags https://gobyexample.com/command-line-flags
> 
> And in this loop: [feff9eb#diff-2ceec6071e325b949b0bccb33ceb78b914835960a97b33f64912882cf3d22b28R154](https://github.com/SegoCode/swd/commit/feff9eb52aae1fcbfb8b955a8fcd132b38a2ead8#diff-2ceec6071e325b949b0bccb33ceb78b914835960a97b33f64912882cf3d22b28R154)
> 
> Maybe you should add +1 to the actual node to show the next node to try in the output
> 
> And again thank you for contributing 💕

oh, i forgot to edit this, thanks 
https://github.com/SegoCode/swd/commit/feff9eb52aae1fcbfb8b955a8fcd132b38a2ead8#diff-2ceec6071e325b949b0bccb33ceb78b914835960a97b33f64912882cf3d22b28R154

and will see https://gobyexample.com/command-line-flags

**Pull request merged**
